---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Centos)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks: 

  - name: install apache and php  for Ubuntu servers
    apt:
      name:
        - apache
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php for CentOS servers
    dnf:
      name: 
        - httpd
        - php
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:

  - name: install db  packages (Centos)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Centos"
  - name:
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba server in file servers
    package:
      name: samba
      state: latest 
