---

- hosts: all
  become: true
  tasks:
 
  - name: install httpd and PHP package
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: add php support for apache
    yum:
      name: mod_ssl
      state: latest
