---

- hosts: all
  become: true
  tasks:
  - name: update repositiry index
    yum:
      update_cache: yes

  - name: install apache2 package
    yum:
      name: httpd
      state: latest

  - name: add php support for apache
    yum:
      name: mod_ssl
      state: latest
  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
