---

- hosts: all
  become: true
  tasks:
  - name: update repositiry index
    yum:
      update_cache: yes

  - name: install apache2 package
    yum:
      name: httpd
      state: absent

  - name: add php support for apache
    yum:
      name: mod_ssl
      state: absent
